### PR TITLE
Preventing speed change caused by dblclick event

### PR DESCRIPTION
**Pull request by denilsonsa**
It is not needed anyway. And clicking fast enough will trigger 2 `click` events followed by a `dblclick`, leading to 3 increments instead of the expected 2.

### CODE REVIEW

**Comment by benedictchen** [comment]
Thanks for the PR.  The rationale for putting the double click listener is because if a user clicks fast enough, the OS thinks it's a double click and will send that event through the browser.  The net effect is that nothing will happen when clicking too fast.  The solution would be to increase the threshold for double clicking, which is controlled on the OS settings side.

**Comment by denilsonsa** [comment]
Oh, so what we want is to run `ev.preventDefault()` on `dblclick`, to avoid selecting the elements, but NOT run `clickHandler`. Is it right?

Also, if the idea is to just prevent accidental selection, we can use [`user-select`](https://css-tricks.com/almanac/properties/u/user-select/).

**Comment by denilsonsa** [comment]
Okay, tested it. Now double-click does not trigger full-screen on YouTube, and also does not cause additional changes to the speed. I've also removed [non-standard cancelBubble](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/cancelBubble) attribute.

**Comment by denilsonsa** [comment]
Merge conflicts fixed.

**Comment by benedictchen** [comment]
I'm gonna merge this, but I don't have time to test it right now so that'll wait until the next release until it gets deployed.

**Pull request merged**
